### ISSUE TITLE
These are all malware, don't download!

### ISSUE THREAD

**Issue by Frogg3rsMC** [ManInMyVan/meteor-archive#6]
ive just checked all of these for malware, and the contain rats and external network connectors that aren't needed! just compile the real meteor with the tutorial!!

**Comment by ManInMyVan** [comment]
this is probably a joke, but incase it isn't

> ive just checked all of these for malware, and the contain rats and external network connectors that aren't needed!

typically how antivirus scans on jars with obfuscated (minecraft) code goes, if you download latest meteor client from the official website, you'll get the same or similar results

> external network connectors

probably the meteor api (update checking, capes)

> bleach

wrong client

**Comment by Frogg3rsMC** [comment]
gang, ive compared it with the real meteor, these are all malware and contain foreign code.

**Comment by ManInMyVan** [comment]
> gang, ive compared it with the real meteor, these are all malware and contain foreign code.

I doubt that

**Comment by Frogg3rsMC** [comment]
theres multiple changes if you were to compile it yourself, and i used a wayback to get the original meteor. Why are you ratting people?

**Comment by ManInMyVan** [comment]
> theres multiple changes if you were to compile it yourself, and i used a wayback to get the original meteor. Why are you ratting people?
> 

I'm not? Compare the hashes to the original meteor jar?
