### ISSUE TITLE
all of this is malware stop deleting my comments lil bro 

### ISSUE THREAD

**Issue by Frogg3rsMC** [ManInMyVan/meteor-archive#7]
there is netowrk handlers that meteor does NOT need its malware bro its malware its malware its malware just build meteor yourself

**Comment by ManInMyVan** [comment]
> there is netowrk handlers that meteor does NOT need

like?

**Comment by BloodyNora** [comment]
I happened to crosscheck checksums for 0.5.6 between this archive and the mvnrepository.com listing as well as the public maven instance of the meteor team. these match :-D

i then crosschecked 0.5.8 from the meteor website against aforementioned repositories. they matched. 

fairly sure it's not overly hard to recreate what i described above.

maybe @Frogg3rsMC is just FUDing ;-)
